import 'moment-timezone';
import 'moment';
import 'bootstrap-switch';
import 'bootstrap/js/collapse';
import 'bootstrap/js/modal';
import 'bootstrap/js/tooltip';
import 'bootstrap/js/popover';
import 'bootstrap-colorpicker';
import './views/html/main.js';
