import './lib/bootstrap-colorpicker.css';
import './lib/prettify.css';
import 'bootstrap/less/bootstrap.less';
import './lib/bootstrap-switch.css';
import './lib/jquery.splitter.css';
import './structure/overrides.css';
import './structure/layout.css';
import './structure/utils.css';
import './themes/classic.css';
