/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/generateConfig.mjs
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2018
* @license Apache-2.0
*/
import ToBase64 from "../../operations/ToBase64";
import FromBase64 from "../../operations/FromBase64";

let OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.Default = {
    "To Base64": ToBase64,
    "From Base64": FromBase64,
};

export default OpModules;
