name: "Master Build, Test & Deploy"

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  main:
    permissions:
      contents: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set node version
        uses: actions/setup-node@v6
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"

      - name: Install
        run: |
          npm install
          npm run setheapsize

      - name: Lint
        run: npm run lint

      - name: Unit Tests
        run: |
          npm test
          npm run testnodeconsumer

      - name: Production Build
        if: success()
        run: npm run build

      - name: Generate sitemap
        run: npm run build:sitemap

      - name: Install Playwright Browsers
        if: success()
        run: npx playwright install --with-deps chromium

      - name: UI Tests
        if: success()
        run: npm run testui

      - name: Prepare for GitHub Pages
        if: success()
        run: npm run build:ghpages

      - name: Deploy to GitHub Pages
        if: success() && github.ref == 'refs/heads/master'
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: ./build/prod
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
